# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1dd0c8cf4fa4a316c097ae1fe7d92e553f0cbe3036dc762e2db2fcd87a334446a6dc78c424b0625a1df373c38b5b21556f5201271bb6b1bf13aba011486417f6

test:
  secret_key_base: 433e7b9eff3caa3fc4249667330c033d583ea7090c2157cfbfef0977a49daac223469efda7e2cb1e9aa5e69d07e114fbad1089eeca463340f712f3c2f5f14489

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
